title: Anurag Sagar Kumar # your name (or website title) here
logo: "/github.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Frontend Developer
  <br><br>
  <a href="mailto:anurag5122sagr@gmail.com">anurag5122sagar@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/anuragsagarkumar/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/AnuragSagarKumar/">Gihub</a> 
theme: jekyll-theme-minimal
